update docker-hub build procedure

diff --git a/hooks/post_checkout b/hooks/post_checkout
--- a/hooks/post_checkout
+++ b/hooks/post_checkout
@@ -1,10 +1,29 @@
 #!/bin/bash
 # hooks/post_checkout
-# https://docs.docker.com/docker-cloud/builds/advanced/
+# - https://docs.docker.com/docker-cloud/builds/advanced/
+# - https://stackoverflow.com/questions/54578066/how-to-build-a-docker-image-on-a-specific-architecture-with-docker-hub.
 
+## Unshallow the repository to get all the tags.
 if [ -f $(git rev-parse --git-dir)/shallow ]; then
     echo "[***] Unshallowing to get correct tags to work."
     git fetch --tags --unshallow --quiet origin
 else
     echo "[***] Not a shallow repository."
 fi
+
+## Check to see if we're building a different architecture
+BUILD_ARCH=$(echo "${DOCKERFILE_PATH}" | cut -d '.' -f 2)
+
+[ "${BUILD_ARCH}" == "Dockerfile" ] && \
+    { echo 'qemu-user-static: Download not required for current arch'; exit 0; }
+
+QEMU_USER_STATIC_ARCH=$([ "${BUILD_ARCH}" == "armhf" ] && echo "${BUILD_ARCH::-2}" || echo "${BUILD_ARCH}")
+QEMU_USER_STATIC_DOWNLOAD_URL="https://github.com/multiarch/qemu-user-static/releases/download"
+QEMU_USER_STATIC_LATEST_TAG=$(curl -s https://api.github.com/repos/multiarch/qemu-user-static/tags \
+    | grep 'name.*v[0-9]' \
+    | head -n 1 \
+    | cut -d '"' -f 4)
+
+echo "[***] Downloading ${QEMU_USER_STATIC_DOWNLOAD_URL}/${QEMU_USER_STATIC_LATEST_TAG}/x86_64_qemu-${QEMU_USER_STATIC_ARCH}-static.tar.gz"
+curl -sL "${QEMU_USER_STATIC_DOWNLOAD_URL}/${QEMU_USER_STATIC_LATEST_TAG}/x86_64_qemu-${QEMU_USER_STATIC_ARCH}-static.tar.gz" \
+    | tar xzv
